### ISSUE TITLE
Easy fee setup for wallet.pay()

### ISSUE THREAD

**Issue by YiumPotato** [blocktrail/blocktrail-sdk-nodejs#17]
how am I supposed to use optimal_fee trying to pay for a tx? Thank you :)
It always pays 0.0001BTC/kB but what if I wanna set it up for 0.0002/kB etc..?

also, it would be awesome if instead of btc/kB its btc/B! Much more dynamic fees, much fun much richer

Love the simplicity, wtg!

**Comment by rubensayshi** [comment]
just published `v2.0.0` which enables using dynamic fees, please make sure to read https://github.com/blocktrail/blocktrail-sdk-nodejs/blob/master/docs/CHANGELOG.md#v200 because it contains some BC breaks.
