### ISSUE TITLE
Cannot upgrade wallet to v3

### ISSUE THREAD

**Issue by michelem09** [blocktrail/blocktrail-sdk-nodejs#35]
I don't know if this is the right place but I didn't find another way to contact you.

I cannot upgrade (or create) a wallet v3 I always receive the error:

> Failed
> Uncaught RangeError: Maximum call stack size exceeded

This happens on both live and test net.

**Comment by rubensayshi** [comment]
Could you tell me the version of NodeJS you are running and maybe a full stack trace of the error? (catch it and then `console.log(err.stack)`

**Comment by michelem09** [comment]
No well, I'm trying that from your website and is your website to response me with that error:

https://www.blocktrail.com/user/tBTC/wallets/<wallet-identifier>/upgrade

**Comment by rubensayshi** [comment]
Okay, so then the question becomes:
Could you tell me what browser (and preferably which version) you are using?

**Comment by michelem09** [comment]
Mac OS Sierra
Google Chrome Version 55.0.2883.95 (64-bit)

http://i.imgur.com/Sa8KVFF.png

**Comment by rubensayshi** [comment]
Could you try it again, we seemed to have some issues with the minifying of the javascript in odd ways ...

**Comment by michelem09** [comment]
Great it works now! Thanks
