### ISSUE TITLE
Custom "fixed" fees?

### ISSUE THREAD

**Issue by michelem09** [blocktrail/blocktrail-sdk-nodejs#37]
I'm looking for a way to pay with a fixed amount of fee per transaction, should this work?

```
wallet.pay({'1NcXPMRaanz43b1kokpPuYDdk6GGDvxT2T': '1000000' }, null, false, true, 1000,
    function(err, result) {});
```

**Comment by rubensayshi** [comment]
just tagged v3.0.1 with a fix for this, the syntax is:

```
wallet.pay({'1NcXPMRaanz43b1kokpPuYDdk6GGDvxT2T': '1000000'}, null, false, true, blocktrail.Wallet.FEE_STRATEGY_FORCE_FEE, null, {
                forcefee: forceFee
            }, function(err, txHash) {});
            
```

really need to rework the method params at some point to make it a bit easier to use ...

**Comment by michelem09** [comment]
Thank you I'm going to try this. I can also suggest a review of the doc (https://www.blocktrail.com/api/docs/lang/nodejs#sending_transactions) that doesn't explain in any way what the params are. (I had to look at the source code, and  I think there is also an error in the comment params.)

**Comment by michelem09** [comment]
This line is dup https://github.com/blocktrail/blocktrail-sdk-nodejs/blob/69d85ea8987178f5c0dde4b85776cfbc22fe943a/lib/wallet.js#L758

**Comment by timigod** [comment]
@rubensayshi that syntax doesn't work. (Assuming I'm right and the variable `forceFee` you're passing into the options object should be the Satoshi value of the fee you're trying to fix).

This is the error I get
```
Error: An internal error was encountered
    at Function.Request.handleFailure (/Users/[redacted]/node_modules/blocktrail-sdk/lib/request.js:210:17)
    at /Users/[redacted]/node_modules/blocktrail-sdk/lib/request.js:184:29
    at Request.callback (/Users/[redacted]/node_modules/superagent/lib/node/index.js:746:30)
    at Request.<anonymous> (/Users/[redacted]/node_modules/superagent/lib/node/index.js:135:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/[redacted]/node_modules/superagent/lib/node/index.js:938:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 500, statusCode: 500
```

Other fee strategies work fine.

Notes: I'm using testnet.

**Comment by rubensayshi** [comment]
hey @timigod 

I made an example here that works: https://github.com/blocktrail/blocktrail-sdk-nodejs/blob/master/examples/wallet_force_fee.js

```js
    wallet.pay(pay, null, false, true, blocktrail.Wallet.FEE_STRATEGY_FORCE_FEE, null, options, function(err, result) {
            if (err) {
                return console.log("pay ERR", err);
            }

            console.log('transaction', result);
        });
```

`options.forcefee` should indeed by satoshis.

if it ain't working maybe you can paste the `wallet.pay` call here so I can try it out?

sorry about the `wallet.pay` method being a bit of a hassle to use, we're planning to redo it with a fluent method API soon, probably coinciding with changing the package name from `blocktrail-sdk` to BTC.com in the near future,

**Comment by timigod** [comment]
Hey @rubensayshi thanks a lot. And there's no need to apologize about the `wallet.pay` method. It's not that much of a hassle, you have removed so much more stress with this SDK and I thank you for that.

The reason it hasn't been working is that I used `options.forceFee` instead of `options.forcefee`, now it works. 

Thanks again!
