### ISSUE TITLE
tBTC network lags

### ISSUE THREAD

**Issue by michelem09** [blocktrail/blocktrail-sdk-nodejs#40]
I'm noticing a lot of lag on new transaction on tBTC network.

I made this transactions 5 minutes ago ddb761abc4c4a59e6f1b644af26e88d98fe4857d1c2b0ceb7f8f7e02b6bf0c41 and I can see it in blockr.io but not in blocktrail.com

Is this supposed to happen in BTC Network too?

**Comment by michelem09** [comment]
Yeah you are right I saw now I have forgotten a 0 when calculating fee. I'm going to do some more tests but it's weird blockr.io have the TX while blocktrail not (receiver address is a blocktrail wallet address)

**Comment by afk11** [comment]
It is weird indeed, thanks for letting us now! I'll test to see if there is a limit we can tweak, or determine if it was sheer luck we didn't hear about it xD

**Comment by michelem09** [comment]
I think tests are simple, if you send a TX with a very low fee (<= 1000) the TX doesn't appear in Blocktrail at all (it takes time) while in blockr.io you should find it almost instantly (few seconds).
