### ISSUE TITLE
Does not run on the latest node v6.10.1 LTS

### ISSUE THREAD

**Issue by anasayubi** [blocktrail/blocktrail-sdk-nodejs#47]
The package does not install on node v6.10.1 LTS with the command `npm install --save blocktrail-sdk 3.*`
Gives errors instead.
![error](https://cloud.githubusercontent.com/assets/8489941/24447800/94e4d5fa-148b-11e7-81ef-8b497c4d1651.png)

**Comment by afk11** [comment]
Did you perhaps mean to run `npm install blocktrail-sdk@3.*`? npm is looking for a package called '3.*' based on your error

**Comment by anasayubi** [comment]
Alright so I did just that but then the terminal just gets stuck. Btw, I'm on Ubuntu 16.04
Also, I ran `npm install --save blocktrail-sdk 3.*` because it is mentioned so at https://www.blocktrail.com/api/docs/lang/nodejs#installation
![error](https://cloud.githubusercontent.com/assets/8489941/24453118/f9f4d274-149f-11e7-81fd-402b15718c4e.png)

**Comment by kamikazechaser** [comment]
If you want to install the lastest version:

`npm install --save blocktrail-sdk`

If you want to install the lastest v3 the correct syntax would be:

`npm install --save blocktrail-sdk^3.0.0`

If you want to install and keep the specific version in your `package.json`:

`npm install --save --save-exact blocktrail-sdk@3.0.10`

**Comment by rubensayshi** [comment]
thx @kamikazechaser somehow i hadn't even noticed he was using the wrong syntax!
