### ISSUE TITLE
Does not run on the latest node v6.3.0 and npm v3.10.3

### ISSUE THREAD

**Issue by anasayubi** [blocktrail/blocktrail-sdk-nodejs#48]
The package does not install on node v6.3.0 and npm v3.10.3 with the command `npm install --save blocktrail-sdk 3.*`
Gives errors instead.
![error](https://cloud.githubusercontent.com/assets/8489941/24448274/10d69378-148d-11e7-9198-0801d1153f18.png)

**Comment by anasayubi** [comment]
I tried running `npm install --save blocktrail-sdk@3.*` instead of `npm install --save blocktrail-sdk 3.*` 
But the the terminal just gets stuck. Internet is working fine, waited for 20 minutes. No change.
I'm on Ubuntu 16.04 btw
![error](https://cloud.githubusercontent.com/assets/8489941/24453582/e67f5d84-14a1-11e7-9096-877a82f1f7b2.png)

**Comment by rubensayshi** [comment]
Can you share the `npm-debug.log` that gets created?

**Comment by anasayubi** [comment]
Just tried it out again and it's working perfectly. Thanks for the time! :)
