### ISSUE TITLE
error in jsdoc of APIClient.prototype.walletTransactions at lib/api_client.js

### ISSUE THREAD

**Issue by ha1331** [blocktrail/blocktrail-sdk-nodejs#52]
/**
 * get all transactions for an address (paginated)
 *
 * @param address       string      address hash
 * @param [params]      array       pagination: {page: 1, limit: 20, sort_dir: 'asc'}
 * @param [cb]          function    callback function to call when request is complete
 * @return q.Promise
 */

it seems to me @param [params] should be of type object, not an array

**Comment by rubensayshi** [comment]
yea it should, probably remnant of building the JS and PHP SDK side by side haha

cleaned up a bunch of them: https://github.com/blocktrail/blocktrail-sdk-nodejs/commit/17eeb7d2afa0c6cfddb124a2c163ede48559e464
