### ISSUE TITLE
IP Banned - StatusCode 403

### ISSUE THREAD

**Issue by Bostrot** [blocktrail/blocktrail-sdk-nodejs#55]
My application just starts receiving status code 403. I did not change anything in the code and API requests number is far below 300k. 

EDIT: Okay, now it says that my IP is banned... Has anyone an idea how to prevent this?

**Comment by Bostrot** [comment]
I just assigned myself a new IP and it got banned again.

**Comment by Bostrot** [comment]
Problem was that i had far too many requests.

**Comment by afk11** [comment]
Usually this is due to calling an API endpoint in a constructor or something, maybe review for unexpected requests that might cause it? 

Can you email support@btc.com about this and mention the wallet + IP ban?
